package modelo;
// Generated 13/04/2013 13:05:43 by Hibernate Tools 3.2.1.GA



/**
 * Certificado generated by hbm2java
 */
public class Certificado  implements java.io.Serializable {


     private String numeroCertificado;
     private Persona personaByIdAhijado;
     private Persona personaByIdPadrino;
     private Persona personaByIdTutor;
     private Persona personaByIdCura;
     private String nombreParroquia;
     private String domicilioParooquia;
     private String telefParroquia;
     private String barrioParroquia;
     private String libro;
     private String folio;
     private String partida;

    public Certificado() {
    }

	
    public Certificado(String numeroCertificado, Persona personaByIdAhijado, Persona personaByIdPadrino, Persona personaByIdTutor, Persona personaByIdCura) {
        this.numeroCertificado = numeroCertificado;
        this.personaByIdAhijado = personaByIdAhijado;
        this.personaByIdPadrino = personaByIdPadrino;
        this.personaByIdTutor = personaByIdTutor;
        this.personaByIdCura = personaByIdCura;
    }
    public Certificado(String numeroCertificado, Persona personaByIdAhijado, Persona personaByIdPadrino, Persona personaByIdTutor, Persona personaByIdCura, String nombreParroquia, String domicilioParooquia, String telefParroquia, String barrioParroquia, String libro, String folio, String partida) {
       this.numeroCertificado = numeroCertificado;
       this.personaByIdAhijado = personaByIdAhijado;
       this.personaByIdPadrino = personaByIdPadrino;
       this.personaByIdTutor = personaByIdTutor;
       this.personaByIdCura = personaByIdCura;
       this.nombreParroquia = nombreParroquia;
       this.domicilioParooquia = domicilioParooquia;
       this.telefParroquia = telefParroquia;
       this.barrioParroquia = barrioParroquia;
       this.libro = libro;
       this.folio = folio;
       this.partida = partida;
    }
   
    public String getNumeroCertificado() {
        return this.numeroCertificado;
    }
    
    public void setNumeroCertificado(String numeroCertificado) {
        this.numeroCertificado = numeroCertificado;
    }
    public Persona getPersonaByIdAhijado() {
        return this.personaByIdAhijado;
    }
    
    public void setPersonaByIdAhijado(Persona personaByIdAhijado) {
        this.personaByIdAhijado = personaByIdAhijado;
    }
    public Persona getPersonaByIdPadrino() {
        return this.personaByIdPadrino;
    }
    
    public void setPersonaByIdPadrino(Persona personaByIdPadrino) {
        this.personaByIdPadrino = personaByIdPadrino;
    }
    public Persona getPersonaByIdTutor() {
        return this.personaByIdTutor;
    }
    
    public void setPersonaByIdTutor(Persona personaByIdTutor) {
        this.personaByIdTutor = personaByIdTutor;
    }
    public Persona getPersonaByIdCura() {
        return this.personaByIdCura;
    }
    
    public void setPersonaByIdCura(Persona personaByIdCura) {
        this.personaByIdCura = personaByIdCura;
    }
    public String getNombreParroquia() {
        return this.nombreParroquia;
    }
    
    public void setNombreParroquia(String nombreParroquia) {
        this.nombreParroquia = nombreParroquia;
    }
    public String getDomicilioParooquia() {
        return this.domicilioParooquia;
    }
    
    public void setDomicilioParooquia(String domicilioParooquia) {
        this.domicilioParooquia = domicilioParooquia;
    }
    public String getTelefParroquia() {
        return this.telefParroquia;
    }
    
    public void setTelefParroquia(String telefParroquia) {
        this.telefParroquia = telefParroquia;
    }
    public String getBarrioParroquia() {
        return this.barrioParroquia;
    }
    
    public void setBarrioParroquia(String barrioParroquia) {
        this.barrioParroquia = barrioParroquia;
    }
    public String getLibro() {
        return this.libro;
    }
    
    public void setLibro(String libro) {
        this.libro = libro;
    }
    public String getFolio() {
        return this.folio;
    }
    
    public void setFolio(String folio) {
        this.folio = folio;
    }
    public String getPartida() {
        return this.partida;
    }
    
    public void setPartida(String partida) {
        this.partida = partida;
    }




}


