package modelo;
// Generated 13/04/2013 13:05:43 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int idPersona;
     private int dni;
     private boolean cura;
     private String apellido;
     private String nombre;
     private String sexo;
     private Date fechaNaciemiento;
     private String lugarNacimiento;
     private String provNacimiento;
     private String nacionalidad;
     private String hijoDe;
     private String domicilio;
     private String barrio;
     private String telefonoFijo;
     private String telefonoCelular;
     private Set certificadosForIdCura = new HashSet(0);
     private Set certificadosForIdAhijado = new HashSet(0);
     private Set certificadosForIdTutor = new HashSet(0);
     private Set certificadosForIdPadrino = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int idPersona, int dni, boolean cura, String sexo) {
        this.idPersona = idPersona;
        this.dni = dni;
        this.cura = cura;
        this.sexo = sexo;
    }
    public Persona(int idPersona, int dni, boolean cura, String apellido, String nombre, String sexo, Date fechaNaciemiento, String lugarNacimiento, String provNacimiento, String nacionalidad, String hijoDe, String domicilio, String barrio, String telefonoFijo, String telefonoCelular, Set certificadosForIdCura, Set certificadosForIdAhijado, Set certificadosForIdTutor, Set certificadosForIdPadrino) {
       this.idPersona = idPersona;
       this.dni = dni;
       this.cura = cura;
       this.apellido = apellido;
       this.nombre = nombre;
       this.sexo = sexo;
       this.fechaNaciemiento = fechaNaciemiento;
       this.lugarNacimiento = lugarNacimiento;
       this.provNacimiento = provNacimiento;
       this.nacionalidad = nacionalidad;
       this.hijoDe = hijoDe;
       this.domicilio = domicilio;
       this.barrio = barrio;
       this.telefonoFijo = telefonoFijo;
       this.telefonoCelular = telefonoCelular;
       this.certificadosForIdCura = certificadosForIdCura;
       this.certificadosForIdAhijado = certificadosForIdAhijado;
       this.certificadosForIdTutor = certificadosForIdTutor;
       this.certificadosForIdPadrino = certificadosForIdPadrino;
    }
   
    public int getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(int idPersona) {
        this.idPersona = idPersona;
    }
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public boolean isCura() {
        return this.cura;
    }
    
    public void setCura(boolean cura) {
        this.cura = cura;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getFechaNaciemiento() {
        return this.fechaNaciemiento;
    }
    
    public void setFechaNaciemiento(Date fechaNaciemiento) {
        this.fechaNaciemiento = fechaNaciemiento;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public String getProvNacimiento() {
        return this.provNacimiento;
    }
    
    public void setProvNacimiento(String provNacimiento) {
        this.provNacimiento = provNacimiento;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getHijoDe() {
        return this.hijoDe;
    }
    
    public void setHijoDe(String hijoDe) {
        this.hijoDe = hijoDe;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public String getTelefonoCelular() {
        return this.telefonoCelular;
    }
    
    public void setTelefonoCelular(String telefonoCelular) {
        this.telefonoCelular = telefonoCelular;
    }
    public Set getCertificadosForIdCura() {
        return this.certificadosForIdCura;
    }
    
    public void setCertificadosForIdCura(Set certificadosForIdCura) {
        this.certificadosForIdCura = certificadosForIdCura;
    }
    public Set getCertificadosForIdAhijado() {
        return this.certificadosForIdAhijado;
    }
    
    public void setCertificadosForIdAhijado(Set certificadosForIdAhijado) {
        this.certificadosForIdAhijado = certificadosForIdAhijado;
    }
    public Set getCertificadosForIdTutor() {
        return this.certificadosForIdTutor;
    }
    
    public void setCertificadosForIdTutor(Set certificadosForIdTutor) {
        this.certificadosForIdTutor = certificadosForIdTutor;
    }
    public Set getCertificadosForIdPadrino() {
        return this.certificadosForIdPadrino;
    }
    
    public void setCertificadosForIdPadrino(Set certificadosForIdPadrino) {
        this.certificadosForIdPadrino = certificadosForIdPadrino;
    }




}


